# Generated by Django 2.1.7 on 2019-02-19 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Servicetype', models.CharField(max_length=250)),
                ('Source', models.CharField(max_length=250)),
                ('Destnation', models.CharField(max_length=250)),
                ('Bookdate', models.DateTimeField()),
                ('Booktime', models.TimeField()),
                ('Pickuptime', models.DateTimeField()),
                ('Driverid', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
                ('fare', models.PositiveIntegerField()),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField(max_length=250)),
                ('canceltime', models.TimeField()),
                ('reasonofcan', models.TextField(max_length=250)),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
    ]
