# Generated by Django 2.1.7 on 2019-02-19 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='roleper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=250)),
                ('perr', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('empId', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('FName', models.CharField(max_length=250)),
                ('MName', models.CharField(max_length=250)),
                ('LName', models.CharField(max_length=250)),
                ('Email', models.EmailField(max_length=250)),
                ('Phone', models.PositiveIntegerField()),
                ('Address', models.TextField()),
                ('MgName', models.CharField(max_length=250)),
                ('Mg_email', models.CharField(max_length=250)),
                ('Location', models.TextField()),
                ('RId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.roleper')),
            ],
        ),
    ]
